# PREFIX
# set -g prefix C-a

# 256 COLORS
set -g default-terminal "xterm-256color" # for apps inside tmux
set -a terminal-overrides ",*256col*:RGB" # adds RGB if 256col in our terminal

# APPEREANCE
# set -g status-style bg=colour235,fg=white # another style for bg
# set -g status-position top
# set -g status-justify absolute-centre
set -g status-style 'fg=color8 bg=default' # default style
set -g status-left-length 100 # larger length for left side
set -g status-right '#(whoami)@#h' # login@host
setw -g window-status-current-style 'fg=colour6 bg=default bold' # color for active window
setw -g window-status-current-format '#I:#W ' # remove * from active window
setw -g window-status-style 'fg=color8' # default style for non-active window

# BINDINGS
bind r source-file ~/.config/tmux/tmux.conf \; display "config sourced"

unbind %
bind | split-window -h 
unbind '"'
bind - split-window -v

bind h select-pane -L # vim like movements
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5 # vim like resizing
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# OPTIONS
setw -g mode-keys vi # vim like movements in copy mode
bind -T copy-mode-vi v send -X begin-selection # v starts selection mode like in vim
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard' # y copies to clipboard
# проверить, будет ли работать по ssh, если нет - возможно понадобится tmux-yank

set -g base-index 1 # 1-indexing for windows
set -g pane-base-index 1 # 1-indexing for panes
set -g renumber-windows on # renumbing windows after closing
# set -g repeat-time 500 # disable timing after command
set -g escape-time 0 # disable delay after escape
set -g mouse on # enable mouse
set -g history-limit 10000 # more history lines in buffer

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# PLUGINS SETTINGS
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'
# set -g @resurrect-strategy-vim 'session'
# set -g @resurrect-strategy-nvim 'session'

run '~/.config/tmux/plugins/tpm/tpm'
